// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_proto/user.proto

package users

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValidateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa82d319f76b864e, []int{0}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ValidateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ValidateResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateResponse) Reset()         { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()    {}
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa82d319f76b864e, []int{1}
}

func (m *ValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse.Unmarshal(m, b)
}
func (m *ValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse.Marshal(b, m, deterministic)
}
func (m *ValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse.Merge(m, src)
}
func (m *ValidateResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse.Size(m)
}
func (m *ValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse proto.InternalMessageInfo

func (m *ValidateResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*ValidateRequest)(nil), "users.ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "users.ValidateResponse")
}

func init() { proto.RegisterFile("user_proto/user.proto", fileDescriptor_aa82d319f76b864e) }

var fileDescriptor_aa82d319f76b864e = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x2d, 0x4e, 0x2d,
	0x8a, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x07, 0x31, 0xf5, 0xc0, 0x4c, 0x21, 0x56, 0x10, 0xbb,
	0x58, 0xc9, 0x9a, 0x8b, 0x3f, 0x2c, 0x31, 0x27, 0x33, 0x25, 0xb1, 0x24, 0x35, 0x28, 0xb5, 0xb0,
	0x34, 0xb5, 0xb8, 0x44, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51,
	0x83, 0x33, 0x08, 0xcc, 0x16, 0x12, 0xe1, 0x62, 0x4d, 0xcd, 0x4d, 0xcc, 0xcc, 0x91, 0x60, 0x02,
	0x0b, 0x42, 0x38, 0x4a, 0x1a, 0x5c, 0x02, 0x08, 0xcd, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0x60, 0x95,
	0x65, 0x20, 0x31, 0xb0, 0x76, 0x8e, 0x20, 0x08, 0xc7, 0xc8, 0x95, 0x8b, 0x25, 0xb4, 0x38, 0xb5,
	0x48, 0xc8, 0x96, 0x8b, 0x03, 0xa6, 0x43, 0x48, 0x4c, 0x0f, 0xec, 0x04, 0x3d, 0x34, 0xfb, 0xa5,
	0xc4, 0x31, 0xc4, 0x21, 0x46, 0x2b, 0x31, 0x38, 0xa9, 0x45, 0xa9, 0xa4, 0x67, 0x96, 0x64, 0x94,
	0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x17, 0x14, 0x25, 0xe6, 0xe5, 0x57, 0x66, 0xeb, 0xe7, 0xa6,
	0xa6, 0x96, 0x94, 0x16, 0xe8, 0xa6, 0xa4, 0xe6, 0x42, 0x7c, 0x58, 0x9c, 0xc4, 0x06, 0xf6, 0xa3,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x88, 0xfa, 0xa0, 0xfc, 0x00, 0x00, 0x00,
}
