// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package users

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValidateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{0}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ValidateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ValidateResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateResponse) Reset()         { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()    {}
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{1}
}

func (m *ValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse.Unmarshal(m, b)
}
func (m *ValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse.Marshal(b, m, deterministic)
}
func (m *ValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse.Merge(m, src)
}
func (m *ValidateResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse.Size(m)
}
func (m *ValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse proto.InternalMessageInfo

func (m *ValidateResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type User struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_d570e3e37e5899c5, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ValidateRequest)(nil), "users.ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "users.ValidateResponse")
	proto.RegisterType((*User)(nil), "users.User")
	proto.RegisterType((*Empty)(nil), "users.Empty")
}

func init() { proto.RegisterFile("proto/user.proto", fileDescriptor_d570e3e37e5899c5) }

var fileDescriptor_d570e3e37e5899c5 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x50, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0xed, 0x4a, 0xa3, 0xeb, 0x28, 0x58, 0x82, 0x68, 0xe9, 0x49, 0x82, 0x48, 0x3d, 0x98, 0x2d,
	0x7a, 0x14, 0x2f, 0x82, 0x78, 0x5f, 0xd0, 0x83, 0xb7, 0xd4, 0x0e, 0xba, 0xd8, 0x6c, 0xd2, 0x4c,
	0x22, 0xf4, 0xef, 0x25, 0x93, 0x15, 0x41, 0x4f, 0xde, 0xde, 0x7b, 0x33, 0x6f, 0xe6, 0xf1, 0x60,
	0xe2, 0x83, 0x8b, 0xae, 0x49, 0x84, 0x41, 0x33, 0x94, 0x22, 0x63, 0x52, 0xb7, 0x70, 0xf4, 0x6c,
	0xd6, 0xdd, 0xca, 0x44, 0x6c, 0x71, 0x93, 0x90, 0xa2, 0x94, 0x30, 0xee, 0x8d, 0xc5, 0x69, 0x75,
	0x56, 0xcd, 0xf7, 0x5b, 0xc6, 0xf2, 0x18, 0x04, 0x5a, 0xd3, 0xad, 0xa7, 0x3b, 0x2c, 0x16, 0xa2,
	0xe6, 0x30, 0xf9, 0x31, 0x93, 0x77, 0x3d, 0xf1, 0xe6, 0x67, 0xd6, 0xd8, 0x5e, 0xb7, 0x85, 0xa8,
	0x05, 0x8c, 0x9f, 0x08, 0xc3, 0x3f, 0x6e, 0xef, 0x81, 0x78, 0xb0, 0x3e, 0x6e, 0xaf, 0x37, 0x20,
	0xb2, 0x95, 0xe4, 0x1d, 0xd4, 0xdf, 0xdf, 0xe4, 0x89, 0xe6, 0xf8, 0xfa, 0x57, 0xf6, 0xd9, 0xe9,
	0x1f, 0xbd, 0xc4, 0x52, 0x23, 0x79, 0x09, 0xf5, 0x23, 0xc6, 0x72, 0xea, 0x70, 0x58, 0xe3, 0x0f,
	0xb3, 0x83, 0x81, 0xe5, 0x99, 0x1a, 0x2d, 0xaa, 0xfb, 0x8b, 0x97, 0xf3, 0xb7, 0x2e, 0xbe, 0xa7,
	0xa5, 0x7e, 0x75, 0xb6, 0xf1, 0xc1, 0xf4, 0x6e, 0xfb, 0xd1, 0x58, 0xc4, 0x98, 0xfc, 0xd5, 0x0a,
	0x6d, 0x29, 0x92, 0x96, 0xbb, 0x5c, 0xe5, 0xcd, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x11, 0xc9,
	0x44, 0x44, 0x5e, 0x01, 0x00, 0x00,
}
